version: 0.2

phases:
  install:
    commands:
      - echo Installing Yarn...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update
      - sudo apt-get install yarn
    finally:
      - echo Checking installation...
      - yarn --version
  pre_build:
    commands:
      - yarn install
    finally:
      - yarn stage
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync --delete s3://mywebsitebuild/ s3://themegatruong.com
artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: output-$(date +%Y-%m-%d)
  discard-paths: no
