version: 0.2

phases:
  install:
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn stage
      - yarn serve
  build:
    commands:
      - yarn build
artifacts:
  files:
    - dist/**/*
  name: output-$(date +%Y-%m-%d)
  discard-paths: no
